build: false
version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_folder: C:\projects\stakx

branches:
  except:
    - gh-pages

cache:
  - vendor
  - '%LocalAppData%\Composer'

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\stakx
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --no-interaction --prefer-dist

test_script:
  - cd C:\projects\stakx
  - vendor\bin\phpunit.bat

notifications:
  - provider: Webhook
    url: http://helit.tech:8093/+sujevo-dev/showSuccessfulBuildMessages=always
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
