build: false
version: 0.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_folder: C:\projects\stakx

environment:
  matrix:
    - dependencies: current
      php_ver_target: 5.6
    - dependencies: highest
      php_ver_target: 5.6
    - dependencies: current
      php_ver_target: 7.0
    - dependencies: highest
      php_ver_target: 7.0
    - dependencies: current
      php_ver_target: 7.1
    - dependencies: highest
      php_ver_target: 7.1
    - dependencies: highest
      php_ver_target: 7.2

matrix:
  fast_finish: true

branches:
  except:
    - gh-pages

cache:
  - vendor
  - '%LocalAppData%\Composer'

## Set up environment variables
init:
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y OpenSSL.Light

  # In order to be able to list all the available PHP packages we have to
  # downgrade Chocolatey to version 0.10.13.
  # See https://github.com/chocolatey/choco/issues/1843
  - ps: choco install chocolatey -y --version 0.10.13 --allow-downgrade --force
  - ps: appveyor-retry choco install php --ignore-checksums -y --force --version ((choco search php -r --exact --all-versions| select-string -pattern $Env:php_ver_target | Select-Object -first 1) -replace '[php|]','')

  - cd c:\tools\php*
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini

  - refreshenv
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar config github-oauth.github.com %GH_TOKEN%
  - IF %dependencies%==current php composer.phar install --no-progress --prefer-dist
  - IF %dependencies%==highest php composer.phar update --no-progress --prefer-dist -n
  - php composer.phar show

test_script:
  - cd C:\projects\stakx
  - vendor\bin\phpunit.bat

notifications:
  - provider: Webhook
    url: http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
